# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 淺我的自我開發
author:
  name: 淺我
  twitter: ralphoutlook
  github: ralphoutlook
description: >- # this means to ignore newlines until "baseurl:"
  程式語言的學習，以及一些隨寫紀錄。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ralphoutlook.github.io" # the base hostname & protocol for your site

logo:
  path: "/img/favicons/android-chrome-192x192.png"
  width: 192
  height: 192

analytics:
  google: UA-111464944-2

adsense:
  ad-client: ca-pub-7910474923772750

comments:
  disqus: enhanceralph

# Build settings
paginate: 10 # the number of post per page
#paginate_multiple:
#  - paginate: 10
#    paginate_path: '/web/page:num/'
#    sub_dir: '/web'
#  - paginate: 10
#    paginate_path: '/page:num/'
#    sub_dir: '/'

highlighter: rouge
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed # Possible values -> nested / expanded / compact / compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Handling Reading
exclude:
  - "README.md"
  - "LICENSE"
